---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: "Wait for 'loki' namespace to be active."
      kubernetes.core.k8s_info:
        kind: Namespace
        name: "loki"
      register: namespace_loki
      until:
        - namespace_loki.resources | length > 0
        - namespace_loki.resources[0].status.phase == "Active"
      retries: 30
      delay: 5

    - name: "Assert that 'loki' namespace is active."
      ansible.builtin.assert:
        that:
          - namespace_loki.resources | length > 0
          - namespace_loki.resources[0].status.phase == "Active"
        fail_msg: "Namespace 'loki' is not active."

    - name: "Wait for 'loki' statefulset to be deployed."
      kubernetes.core.k8s_info:
        kind: "StatefulSet"
        name: "loki"
        namespace: "loki"
      register: loki_statefulset
      until: loki_statefulset.resources[0].status.availableReplicas | default(0) == 1
      retries: 30
      delay: 5

    - name: "Assert that 'loki' is deployed."
      ansible.builtin.assert:
        that: loki_statefulset.resources[0].status.availableReplicas | default(0) == 1
        fail_msg: "StatefulSet 'loki' is not deployed."
