---
# tasks file for grafana
- name: "Include setup when enabled"
  ansible.builtin.include_tasks: "setup.yml"
  when: grafana_enabled

- name: "Include cleanup when disabled"
  ansible.builtin.include_tasks: "cleanup.yml"
  when: not grafana_enabled
