namespace: plopoyop
name: kubernetes_observability
version: 1.2.0
readme: README.md
authors:
  - Clément Hubert <clement@plopoyop.me>
description: >-
  Ansible collection to configure observability application on a Kubernetes
  cluster
license_file: LICENSE
tags:
  - cloud
  - kubernetes
  - cluster
  - infrastructure
  - observability
  - opentelemetry
  - grafana
  - victoriametrics
  - loki
repository: 'https://github.com/plopoyop/ansible-collection-kubernetes_observability'
issues: 'https://github.com/plopoyop/ansible-collection-kubernetes_observability/issues'
