---
- name: "Converge"
  hosts: "localhost"
  connection: "local"
  gather_facts: false
  vars:
    jaeger_enabled: false
  tasks:
    - name: "Call jaeger role"
      ansible.builtin.import_role:
        name: "jaeger"
