---
# vars file for grafana
grafana_helm_repo_name: "grafana-community"
grafana_helm_repo_url: "https://grafana-community.github.io/helm-charts"

grafana_helm_chart_ref: "{{ grafana_helm_repo_name }}/grafana"
