---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: "Wait for 'opentelemetry' namespace to be removed."
      kubernetes.core.k8s_info:
        kind: "Namespace"
        name: "opentelemetry"
      register: namespace_opentelemetry
      until: namespace_opentelemetry.resources | length == 0
      retries: 30
      delay: 5

    - name: "Assert that 'opentelemetry' namespace is removed."
      ansible.builtin.assert:
        that: namespace_opentelemetry.resources | length == 0
        fail_msg: "Namespace 'opentelemetry' is still present."

    - name: "Wait for 'opentelemetry operator' deployment to be removed."
      kubernetes.core.k8s_info:
        kind: "Deployment"
        name: "otel-collector-opentelemetry-operator"
        namespace: "opentelemetry"
      register: otel_operator
      until: otel_operator.resources | length == 0
      retries: 30
      delay: 5

    - name: "Assert that 'opentelemetry operator' is removed."
      ansible.builtin.assert:
        that: otel_operator.resources | length == 0
        fail_msg: "Deployment 'otel-collector-opentelemetry-operator' is still present."
