---
driver:
  name: default
platforms:
  - name: molecule-test
provisioner:
  name: ansible
  inventory:
    host_vars:
      localhost:
        ansible_python_interpreter: '{{ ansible_playbook_python }}'
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
  env:
    KUBECONFIG: ~/.kube/config-molecule-test
    K8S_AUTH_KUBECONFIG: ~/.kube/config-molecule-test

dependency:
  name: galaxy
  options:
    role-file: meta/requirements.yml

scenario:
  name: default
  test_sequence:
    - dependency
    - destroy
    - create
    - converge
    - idempotence
    - verify
    - destroy
