---
- name: "Remove Loki instance"
  kubernetes.core.helm:
    name: "{{ loki_release_name }}"
    namespace: "{{ loki_namespace }}"
    chart_ref: "{{ loki_helm_chart_ref }}"
    state: "absent"
    wait: true

- name: "Pause for job to complete."
  ansible.builtin.pause:
    seconds: 30

- name: "Remove Loki namespace"
  kubernetes.core.k8s:
    name: "{{ loki_namespace }}"
    api_version: "v1"
    kind: "Namespace"
    state: "absent"
