---
# tasks file for loki
- name: "Include setup when enabled"
  ansible.builtin.include_tasks: "setup.yml"
  when: loki_enabled

- name: "Include cleanup when disabled"
  ansible.builtin.include_tasks: "cleanup.yml"
  when: not loki_enabled
