---
- name: "Include setup when enabled"
  ansible.builtin.include_tasks:
    file: "setup.yml"
    apply:
      tags:
        - "jaeger"
        - "install"
  when: jaeger_enabled
  tags: ["always"]

- name: "Include cleanup when disabled"
  ansible.builtin.include_tasks:
    file: "cleanup.yml"
    apply:
      tags:
        - "jaeger"
        - "uninstall"
  when: not jaeger_enabled
  tags: ["always"]
