---
- name: "Verify"
  hosts: "localhost"
  connection: "local"
  gather_facts: true

  tasks:
    - name: "Wait for 'jaeger' namespace to be active."
      kubernetes.core.k8s_info:
        kind: "Namespace"
        name: "jaeger"
      register: namespace_jaeger
      until:
        - namespace_jaeger.resources | length > 0
        - namespace_jaeger.resources[0].status.phase == "Active"
      retries: 30
      delay: 5

    - name: "Assert that 'jaeger' namespace is active."
      ansible.builtin.assert:
        that:
          - namespace_jaeger.resources | length > 0
          - namespace_jaeger.resources[0].status.phase == "Active"
        fail_msg: "Namespace 'jaeger' is not active."

    - name: "Wait for 'jaeger' deployment to be deployed."
      kubernetes.core.k8s_info:
        kind: "Deployment"
        name: "jaeger"
        namespace: "jaeger"
      register: jaeger_deployment
      until: jaeger_deployment.resources[0].status.availableReplicas | default(0) == 1
      retries: 30
      delay: 5

    - name: "Assert that 'jaeger' is deployed."
      ansible.builtin.assert:
        that: jaeger_deployment.resources[0].status.availableReplicas | default(0) == 1
        fail_msg: "Deployment 'jaeger' is not deployed."
