---
- name: "Include Single install enabled"
  ansible.builtin.include_tasks:
    file: "single.yml"
  when: victoriametrics_single_enabled
  tags: ["always"]

- name: "Include VMagent install enabled"
  ansible.builtin.include_tasks:
    file: "vmagent.yml"
  when: victoriametrics_vmagent_enabled
  tags: ["always"]
