---
- name: "Include Single install enabled"
  ansible.builtin.include_tasks:
    file: "single.yml"
    apply:
      tags:
        - "victoriametrics"
        - "victoriametrics_single"
        - "install"
  when: victoriametrics_single_enabled
  tags: ["always"]

- name: "Include VMagent install enabled"
  ansible.builtin.include_tasks:
    file: "vmagent.yml"
    apply:
      tags:
        - "victoriametrics"
        - "victoriametrics_vmagent"
        - "install"
  when: victoriametrics_vmagent_enabled
  tags: ["always"]
