---
- name: "Include Single install enabled"
  ansible.builtin.include_tasks: "single.yml"
  when: victoriametrics_single_enabled
  tags:
    - "victoriametrics"
    - "victoriametrics_single"
    - "install"

- name: "Include VMagent install enabled"
  ansible.builtin.include_tasks: "vmagent.yml"
  when: victoriametrics_vmagent_enabled
  tags:
    - "victoriametrics"
    - "victoriametrics_vmagent"
    - "install"
