---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    loki_enabled: false
  tasks:
    - name: "Call loki role"
      ansible.builtin.import_role:
        name: "loki"
