---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    cloud_provider: "{{ lookup('env', 'DEVENV_DOTFILE') }}/bin/cloud-provider-kind"
    loki_storage_type: "filesystem"
    loki_schema_config:
      configs:
        - from: "2024-04-01"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
  tasks:
    - name: Build a kind cluster (wait for control plane).
      ansible.builtin.command: >-
        kind create cluster
        --wait 300s
        --name molecule-test
        --kubeconfig {{ kubeconfig }}
      changed_when: true
    - name: "Call loki role"
      ansible.builtin.import_role:
        name: "loki"
