---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    grafana_admin_password: "admin"
  tasks:
    - name: "Call grafana role"
      ansible.builtin.import_role:
        name: "grafana"
