---
# vars file for loki
loki_grafana_helm_repo_name: "grafana-community"
loki_grafana_helm_repo_url: "https://grafana-community.github.io/helm-charts"
loki_helm_chart_ref: "{{ loki_grafana_helm_repo_name }}/loki"
