---
name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "5 4 * * *"

jobs:
  renovate:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v42.0.1
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_USERNAME: "renovate[bot]"
          LOG_LEVEL: debug
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: "renovate.json"
